### ISSUE TITLE
Your repository is being used in phishing site

### ISSUE THREAD

**Issue by RadxaYuntian** [FilipePS/TWP---Source-Maps#1]
This can be check from browser debugger: http://zoom-meetup-4934.pages.dev/join.html (additional parameters necessary for the page to work are redacted)

![image](https://github.com/user-attachments/assets/4143f32b-6358-423d-8305-07d5a12ffcad)

Right now we are not sure if the URI is hardcoded by the scammer or is pulled by an innocent 3rd party library, though we lean on the first one.

**Comment by FilipePS** [comment]
If you have the TWP - Translate Web Pages extension this will appear on any website.
The extension's scripts include sourcemaps to make debugging easier. And the reason for remote source maps is to reduce the size of the extension's download file and because I believe local sourcemaps were the reason for some performance issues reported by some people in previous versions.

**Comment by RadxaYuntian** [comment]
Thanks. I was not aware that this is how it works.
